server:
  port: 8081
  servlet:
    context-path: /

spring:
  application:
    name: redirection-service
  boot:
    admin:
      client:
        url: http://localhost:9000
  kafka:
    bootstrap-servers: localhost:9094
  data:
    mongodb:
      port: 27017
      host: localhost
      database: url_shortener

springdoc:
  api-docs:
    path: /api-docs

management:
  endpoints:
    web:
      exposure:
        include: "*"

producer:
  click-details:
    topic-name: click-details