server:
  port: 8083
  servlet:
    context-path: /

spring:
  application:
    name: id-generator-service
  boot:
    admin:
      client:
        url: http://localhost:9000

springdoc:
  api-docs:
    path: /api-docs

management:
  endpoints:
    web:
      exposure:
        include: "*"

id:
  length: 7