version: '3'

services:

  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  shorten-service:
    image: shorten-service:latest
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Dspring.profiles.active=docker
      - SERVICE_NAME=shorten-service
    depends_on:
      - mongodb

  redirection-service:
    image: redirection-service:latest
    ports:
      - "8081:8081"
    environment:
      - JAVA_OPTS=-Dspring.profiles.active=docker
      - SERVICE_NAME=redirection-service
    depends_on:
      - mongodb
      - kafka

  analytics-service:
    image: analytics-service:latest
    ports:
      - "8082:8082"
    environment:
      - JAVA_OPTS=-Dspring.profiles.active=docker
      - SERVICE_NAME=analytics-service
    depends_on:
      - kafka

  admin:
    image: admin:latest
    ports:
      - "9000:9000"
    environment:
      - JAVA_OPTS=-Dspring.profiles.active=docker
      - SERVICE_NAME=admin

  kafka:
    image: docker.io/bitnami/kafka:3.6
    ports:
      - "9094:9094"
    volumes:
      - kafka_data:/bitnami
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes

volumes:
  kafka_data:
  mongo_data:
