version: '3'

services:

  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  shorten-service:
    image: shorten-service:latest
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Dspring.profiles.active=docker
      - SERVICE_NAME=shorten-service
    depends_on:
      - mongodb

  redirection-service:
    image: redirection-service:latest
    ports:
      - "8081:8081"
    environment:
      - JAVA_OPTS=-Dspring.profiles.active=docker
      - SERVICE_NAME=redirection-service
    depends_on:
      - mongodb
      - kafka

  analytics-service:
    image: analytics-service:latest
    ports:
      - "8082:8082"
    environment:
      - JAVA_OPTS=-Dspring.profiles.active=docker
      - SERVICE_NAME=analytics-service
    depends_on:
      - kafka

  admin:
    image: admin:latest
    ports:
      - "9000:9000"
    environment:
      - JAVA_OPTS=-Dspring.profiles.active=docker
      - SERVICE_NAME=admin

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka-data:/var/lib/kafka/data

volumes:
  kafka-data:
  mongo-data: