server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: shorten-service
  boot:
    admin:
      client:
        url: http://localhost:9000
  data:
    mongodb:
      port: 27017
      host: localhost
      database: url_shortener

springdoc:
  api-docs:
    path: /api-docs

management:
  endpoints:
    web:
      exposure:
        include: "*"

api:
  id-generator-service:
    address: http://localhost:8083
    rest: ${api.id-generator-service.address}/api
