server:
  port: 8082

spring:
  application:
    name: analytics-service
  boot:
    admin:
      client:
        url: http://localhost:9000
  kafka:
    consumer:
      bootstrap-servers: localhost:9094
      auto-offset-reset: latest
  jmx:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
